"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n%acb$(=5+8hu!kdtu6bzw$p(*-3&2r(zg)^ngxgni(y=ik2pl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'newsportal',
    'django_filters',
    'sign',
    'protect',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    #'appointments',
    'appointments.apps.AppointmentConfig',

]

SITE_ID = 1

LOGIN_URL = 'sign/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware'


]

DEFAULT_FROM_EMAIL = 'agalarov.al@yandex.ru'

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'

LANGUAGE_CODE = 'ru'

#TIME_ZONE = 'UTC'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

LOGIN_REDIRECT_URL = '/news/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'


ACCOUNT_FORMS = {'signup': 'sign.models.BasicSignupForm'}


EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'agalarov.al'
EMAIL_HOST_PASSWORD = 'Agalarov2004'
EMAIL_USE_SSL = True

ADMINS = [
     ('Mail', 'aliagalar228@gmail.com'),
    ('Yandex', 'agalarov.al@yandex.ru')
]

MANAGERS =[
    ('Mail', 'aliagalar228@gmail.com'),
    ('Yandex', 'agalarov.al@yandex.ru')
]

SERVER_EMAIL = 'agalarov.al@yandex.ru'  # это будет у нас вместо аргумента FROM в массовой рассылке

# Модуль 6.3 - подтверждение регистрации через почту
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_AUTHENTIFICTION_METHOD = 'email'

CELERY_BROKER_URL = 'redis://:KmnsMptFfo6EZjarJ0vNdwFH7WfsM8lr@redis-13999.c11.us-east-1-3.ec2.cloud.redislabs.com:13999/0'
CELERY_RESULT_BACKEND = 'redis://:KmnsMptFfo6EZjarJ0vNdwFH7WfsM8lr@redis-13999.c11.us-east-1-3.ec2.cloud.redislabs.com:13999/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CACHES = {
    'default': {
        'TIMEOUT': 30,  # добавляем стандартное время ожидания в минуту (по умолчанию это 5 минут — 300 секунд)
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'),  # BASE_DIR - значит папка проекта Указываем, куда
        # будем сохранять кэшируемые файлы! Не забываем создать папку cache_files внутри папки с manage.py!
    }
}

LOGGING = {
    'version': 1,  # 1
    'disable_existing_loggers': False,  # 2
    'formatters': {  # 3

        # 1-3 пункт задания
        # для уровня DEBUG - время, уровень логирования, сообщение
        'debug_console': {  # 4
            # 'format': '{asctime} :: {levelname} -- {message}',
            'format': '%(asctime)s %(levelname)s %(pathname)s %(message)s',
        },
        # для уровня WARNING - время, уровень логирования, путь к событию, сообщение
        'warning_console': {
            'format': '%(asctime)s %(levelname)s %(pathname)s %(message)s'
        },

        # 3 пункт задания
        # для уровней ERROR и CRITICAL - время, уровень логирования, путь к событию, сообщение, стэк ошибки
        # для файла errors.log
        'error_critical': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s'
        },

        # 2-4 пункт задания - время, уровень логирования, модуль, сообщение
        # для файлов general.log и security.log
        'general_security_log': {
            'format': '%(asctime)s %(levelname)s %(module)s %(message)s'
        },

        # 5 пункт задания - время, уровень логирования, путь к событию, сообщение
        # для уровня ERROR, для отправки по почте
        'mail_log': {
            'format': '%(asctime)s %(levelname)s %(pathname)s %(message)s'
        }
    },

    'filters': {  # 5
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },

    'handlers': {  # 6

        # 1 пункт задания - уровень DEBUG, фильтр DEBUG = True везде, кроме отправки по почте и
        # записи в файл general.log
        'console_debug': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'debug_console'
        },
        'console_warning': {
            'level': 'WARNING',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'warning_console'
        },

        # 2 пункт задания, уровень INFO, фильтр DEBUG = False
        'file_general': {
            'level': 'INFO',
            'filters': ['require_debug_false'],
            'class': 'logging.FileHandler',
            'filename': 'general.log',
            'formatter': 'general_security_log'
        },

        # 4 пункт задания, уровень INFO
        'file_security': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'security.log',
            'formatter': 'general_security_log'
        },

        # 3 пункт задания - уровень ERROR, вывод в файл errors.log
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'errors.log',
            'formatter': 'error_critical'
        },

        # 3 пункт задания - уровень CRITICAL, вывод в файл errors.log
        'file_critical': {
            'level': 'CRITICAL',
            'class': 'logging.FileHandler',
            'filename': 'errors.log',
            'formatter': 'error_critical'
        },

        # 5 пункт задания - уровень ERROR, отправка по почте
        'mail_admin': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'mail_log'
        }
    },

    'loggers': {  # 6 формируем логеров

        # 1, 2 пункт задания
        'django': {
            'handlers': ['console_debug', 'console_warning', 'file_general'],
            'propagate': True,
        },

        # 3 пункт задания
        'django.template': {
            'handlers': ['file_errors', 'file_critical'],
            'propagate': True,
        },

        # 3 пункт задания
        'django.db_backends': {
            'handlers': ['file_errors', 'file_critical'],
            'propagate': True,
        },

        # 4 пункт задания
        'django.security': {
            'handlers': ['file_security'],
            'propagate': True,
        },

        # 5, 3 пункт задания
        'django.request': {
            'handlers': ['file_errors', 'file_critical', 'mail_admin'],
            'propagate': True,
        },

        # 5, 3 пункт задания
        'django.server': {
            'handlers': ['file_errors', 'file_critical', 'mail_admin'],
            'propagate': True,
        }
    }
}
